In [1]:
#####################################
#02 Data order, list, df and wrangle#
#Maintainer: Christopher Chan       #
#Date: 2023-05-04                   #
#Version: 0.1.2                     #
#####################################

# Import all necessary packages
import os, sys, re
import random
import pathlib
import numpy as np
import pandas as pd
#import pyarrow as pa

# Load all the paths we might use later
data_raw = pathlib.Path("../data/raw")
data_external = pathlib.Path("../data/external")

## Welcome to 02_Order_Iteration!
Now that we have learnt the basics of python data types and syntax, we can actually work with some data!
Python data are organised in several formats:
- Lists, Arrays <br>
<t> Lists and arrays can hold multiple data within it, lists of lists, and lists of objects can also be made <br>
<t> Lists and arrays are iterable objects, (i.e. you can print it one by one)

- Dictionaries
- Matrixes
- DataFrames

### Lists & Indexing Lists
Lists are lists, you can put data in lists, whether that be string, float, or integers. You can put a list in list, a function in list. You name it!
A list within a list is called a "NESTED LIST"!

Nested List:
- List_AB:
    - List A: 1, "બે", "三"
    - List_B: "Cuatro", 5, "Sechs"

In [2]:
# Let's make some list of numbers
List_A = [1, "બે", "三"]
List_B = list(("Cuatro", 5, "Sechs"))

print(List_A, List_B)
print(type(List_A), type(List_B))

# We can put 2 list into 1 list!
List_AB = [List_A, List_B]

print(List_AB)
print(type(List_AB))

# How do we access list?
List_B[0]
print(f"The first element of List_B is: {List_B[0]}")
print(f"The last element of List_B is: {List_B[-1]}")

# Python counts from 0, List_A has 4 items in it
List_A[3]

[1, 'બે', '三'] ['Cuatro', 5, 'Sechs']
<class 'list'> <class 'list'>
[[1, 'બે', '三'], ['Cuatro', 5, 'Sechs']]
<class 'list'>
The first element of List_B is: Cuatro
The last element of List_B is: Sechs


IndexError: list index out of range

In [ ]:
# Can we access a range of elements?
# Lets combine List_A and List_B into List_C
List_C = List_A + List_B
print(List_C)

print(f"The lenght of our new list is {len(List_C)}")

# But I just want 5 and Sechs?
# [1:4] Starts at 4, stops at 6, 6 is not included
print(List_C[4], List_C[5])
print(List_C[4:6])

[1, 'બે', '三', 'Cuatro', 5, 'Sechs']
The lenght of our new list is 6
5 Sechs
[5, 'Sechs']


### Iteration and for loops
The point of putting data into a list is not only to able to access it easily and organise it
We can also ITERATE through it!
We do a lot of iteration in programming because this is what makes programming data > Excel

In [ ]:
# for loop
for i in List_A:
    print(i)

# Do you want an index maybe?
# Remember python counts from 0
for idx, i in enumerate(List_A):
    print(idx, i)

1
બે
三
0 1
1 બે
2 三


In [ ]:
# Simultaneous iteration
for A, B in zip(List_AB[0], List_AB[1]):
    print(A, B)

1 Cuatro
બે 5
三 Sechs


In [ ]:
# We can change things in a loop!
for i in List_C:
    if type(i) == str:
        print(i)

બે
三
Cuatro
Sechs


In [ ]:
# If and elif (else-if) allows you to create condition within the for loop iteration
for i in List_C:
    if type(i) == str:
        print(f"The data {i} is a string")
    elif type(i) == int:
        print(f"The data {i} is an integer")

print("\n Now with Enumeration")

for idx, j in enumerate(List_C):
    if type(j) == str:
        print(f"The data {j} at position {idx + 1} is a string")
    elif type(j) == int:
        print(f"The data {j} at position {idx + 1} is an integer")

The data 1 is an integer
The data બે is a string
The data 三 is a string
The data Cuatro is a string
The data 5 is an integer
The data Sechs is a string

 Now with Enumeration
The data 1 at position 1 is an integer
The data બે at position 2 is a string
The data 三 at position 3 is a string
The data Cuatro at position 4 is a string
The data 5 at position 5 is an integer
The data Sechs at position 6 is a string


### Numpy arrays & Indexing arrays
Numpy arrays are essentially Lists, but Lists with sizes that cannot be changed <br>
Arrays are more suitable for mathematical application because they ensure size <br>
We can have arrays with from 1-dimension to as many as you want <br>
That means we can use arrays to represent matrixes

In [ ]:
array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A)
print(type(array_A))

# We can access array elements just like we did with List!
print(array_A[0])
print(array_B[0:2])

# We can even fill empty arrays with 1s and 0s and create arrays in our desired shape
# I want an array with 1-dimension of five 1
oneD_array = np.ones(5)
print(oneD_array)

# I want a 3 row and 3 column (3 by 3) matrix with 0s
twoD_array = np.zeros((3, 3))
print(twoD_array)

[1 2 3]
<class 'numpy.ndarray'>
1
[4 5]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# More creative ways of making arrays

# Array range from 0 to 29
array_C = np.arange(30)
print(array_C)

# Array range from 4 to 400 with an interval of 20
# We can see the output is just shy of 400
array_D = np.arange(4, 400, 20)
print(array_D)

# Random 2-dimension array of 5 by 5
random_array = np.random.rand(5, 5)
print(random_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  4  24  44  64  84 104 124 144 164 184 204 224 244 264 284 304 324 344
 364 384]
[[0.21018964 0.40101095 0.04974748 0.56437419 0.67176341]
 [0.55149857 0.17301585 0.33092364 0.1319018  0.99100017]
 [0.3629739  0.75756654 0.06655054 0.00695017 0.43941547]
 [0.0054486  0.20400024 0.74003591 0.24887422 0.89836662]
 [0.06996172 0.80751417 0.24616558 0.34974369 0.26142367]]


In [ ]:
# Random 3-dimesnion array of 10 by 10 by 3 (layer, row, column)
# With maximum integer limit of 500
ThreeD_RandArray = np.random.randint(500, size = (3, 10, 10))
print(ThreeD_RandArray)

[[[ 60 475  60 281 455 405 104  77 331 153]
  [489  31 284 183 293  39 198  26  68 164]
  [494 417 226 405 375 465 228  90  37 140]
  [ 46 372 464  69 406 315 138  21 438 188]
  [281  36   6  33 276  16  36 119 367 184]
  [269 418 252  36 415 412 135 418   0  30]
  [160  70 192 186 184 428 279 231 259 381]
  [402 153 449 240 342 436 435  58 462 360]
  [456 498  81  43 147 415 121 190 298  73]
  [215 208 432 433 104 307 449 201  59 145]]

 [[ 94  29 335  93  13 197  74 493  80 124]
  [237 178 279 343 123 134 448 108  22 116]
  [197 273 467 433 177  17 444  67 366 382]
  [  4   7 325 432 146 145 258 314 471 416]
  [307 336 134 120 139 210 393  56 133 474]
  [196 316 200 358 376 167 265 114 290 143]
  [145 156 473 432 236 480 367 167 183  98]
  [435 170 113  69 306  74 480 197 144 476]
  [358 264 301 393 332 143 383 423 200 393]
  [295 231 423 154  83  49 302 325  93 485]]

 [[ 66 222 110 354 116 485 120 415 290 145]
  [496 394 472 375 343 112  86 422 116 131]
  [133  50  32  48 250 289 2

In [ ]:
# Indexing 1D array
print(array_C[29])
print(array_C[-1])

print(array_C[29] == array_C[-1])

# Indexing 2D arrays
# Row 4, column 4
print(random_array[3, 3])

# Can we find the position from the value?
print(np.where(array_C == 29))

# How about 3-Dimensional arrays?
#[layer, row, column]
print(ThreeD_RandArray[1, 4, 0])

# Finding value from 3D-array position
print(np.where(ThreeD_RandArray == 459))

# I just want the 1st row of all 3 layers
print(ThreeD_RandArray[:, 0, ])

29
29
True
0.24887421511029717
(array([29], dtype=int64),)
307
(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))
[[ 60 475  60 281 455 405 104  77 331 153]
 [ 94  29 335  93  13 197  74 493  80 124]
 [ 66 222 110 354 116 485 120 415 290 145]]


### DataFrames
DataFrames == Tables == spreadsheet == excels <br>
DataFrames is a grid with a value of data in each cell, this table contains rows and column indexed <br>
We will be using the package pandas to create and access dataframes!

In [ ]:
# Pandas DataFrame
# Let's built upon what we just learnt!
# Can we put List_A and List_B into a table?
Table = pd.DataFrame(twoD_array)

Table

0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0

In [ ]:
# We can use multiple type of creating numpy arrays into making a dataframe!

df = pd.DataFrame({"col1": np.array([-4, 2, 3], dtype = np.int64),
                   "col2": np.arange(4, 7, 1, dtype = np.uint64),
                   "col3": np.zeros(3, dtype = np.float64),
                   "col4": np.array([True, False, False], dtype = bool)})
 
#import pyarrow as pa
## Pandas 2.0 and Arrow
#
#df = pd.DataFrame({"col1": pa.array([-193479, 5987349, 1291], type = "int64"),
#                   "col2": pa.array(np.arange(4, 7, 1), type = "uint64"),
#                   "col3": pa.array(np.zeros(3), type = "float64"),
#                   "col4": pa.array([True, False, False], type = "bool")})

print(df)

print(df.info())

   col1  col2  col3   col4
0    -4     4   0.0   True
1     2     5   0.0  False
2     3     6   0.0  False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    3 non-null      int64  
 1   col2    3 non-null      uint64 
 2   col3    3 non-null      float64
 3   col4    3 non-null      bool   
dtypes: bool(1), float64(1), int64(1), uint64(1)
memory usage: 207.0 bytes
None


### Let's look at E&S Data

In [3]:
# Pandas 2.0
ESData = pd.read_csv(f"{data_raw}/ESData_sample.csv", dtype_backend = "pyarrow", sep = ";")

# Pandas 1.0
#ESData = pd.read_csv(f"{data_raw}/ESData_sample.csv", sep = ";")

ESData.sample(n = 8)

FactorId         Name   
20752      4859    CoPro71.1  \
31496      4621     CliInv27   
33492      4705       OHS1.0   
39062      4676    SupSt1.10   
15555      5046    HFat2.1-x   
35875      4842       CoPro6   
47303      4872       PMH4.1   
5685       5019  WatInv1.1-x   

                                                Question                 Date   
20752  Does the company disclose the existence of an ...  2021-12-31 00:00:00  \
31496  Does the company disclose its scope 3 emission...  2021-12-31 00:00:00   
33492  Does the company express a commitment to ensur...  2022-12-31 00:00:00   
39062  Does the company disclose a supplier policy th...  2020-12-31 00:00:00   
15555                             Employee fatality rate  2022-03-31 00:00:00   
35875  Does the company disclose an anti-corruption d...  2023-03-13 00:00:00   
47303  Does the company disclose the existence of str...  2020-12-31 00:00:00   
5685                Total amount of freshwater withdrawn  2021-03-31 00:00:00   

                                      Answer      PublicationDate Restated   
20752                                     No  2023-02-21 00:00:00    False  \
31496                                     No  2023-03-01 00:00:00    False   
33492                                    Yes  2023-04-13 00:00:00    False   
39062                                     No  2023-03-30 00:00:00    False   
15555  0 Fatalities per 200,000 hours worked  2022-12-08 00:00:00    False   
35875                                    Yes  2023-03-14 00:00:00    False   
47303                                     No  2023-03-17 00:00:00    False   
5685                           Not Disclosed  2023-02-14 00:00:00    False   

       AgentId                                     AgentName  AgentGics   
20752       36  Taiwan Semiconductor Manufacturing Co., Ltd.   45301020  \
31496     1269                  The Sherwin-Williams Company   15101050   
33492     1181                    The New York Times Company   50201040   
39062       49                        PT United Tractors Tbk   10102050   
15555       82                               Infosys Limited   45102010   
35875     1132                           Qurate Retail, Inc.   25503030   
47303     1022                         Dominion Energy, Inc.   55103010   
5685        94                                   DLF Limited   60201010   

                                      CountryOfOperation   
20752            CAN,CHN,CYM,DEU,JPN,KOR,NLD,TWN,USA,VGB  \
31496  USA,SWE,GBR,ESP,LTU,CHL,BRA,POL,ITA,MEX,IND,AR...   
33492  ARE,AUS,BRA,CAN,CHE,CHN,DEU,FRA,GBR,HKG,IND,IT...   
39062                                        IDN,SGP,VGB   
15555  ARE,ARG,AUS,AUT,BEL,BGR,BRA,CAN,CHE,CHL,CHN,CZ...   
35875  USA,BEL,BRA,CHL,GBR,IND,DEU,NLD,COL,LUX,IRL,CA...   
47303            USA,CYM,PER,JEY,CAN,NLD,CHE,SGP,PRY,AUS   
5685                                 IND,VGB,ITA,BRA,CYP   

                                     SourceName       SourceType  Page   
20752                                      <NA>             <NA>  <NA>  \
31496                                      <NA>             <NA>  <NA>   
33492                        2022 Annual Report    Annual Report    14   
39062                                      <NA>             <NA>  <NA>   
15555              Infosys ESG databook 2021/22  Company website    23   
35875  ANTI-BRIBERY AND ANTI-CORRUPTION POLICY            Policy     2   
47303                                      <NA>             <NA>  <NA>   
5685                                       <NA>             <NA>  <NA>   

      Comment                                            Excerpt   
20752    <NA>                                               <NA>  \
31496    <NA>                                               <NA>   
33492    <NA>  Supporting employees’ health, safety and well-...   
39062    <NA>                                               <NA>   
15555    <NA>                                               <

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
