In [2]:
#####################################
#02 Data order, list, df and wrangle#
#Maintainer: Christopher Chan       #
#Date: 2023-05-04                   #
#Version: 0.1.2                     #
#####################################

# Import all necessary packages
import os, sys, re
import random
import pathlib
import numpy as np
import pandas as pd
#import pyarrow as pa

# Load all the paths we might use later
data_raw = pathlib.Path("../data/raw")
data_external = pathlib.Path("../data/external")

## Welcome to 02_Order_Iteration!
Now that we have learnt the basics of python data types and syntax, we can actually work with some data!
Python data are organised in several formats:
- Lists, Arrays <br>
<t> Lists and arrays can hold multiple data within it, lists of lists, and lists of objects can also be made <br>
<t> Lists and arrays are iterable objects, (i.e. you can print it one by one)

- Dictionaries
- Matrixes
- DataFrames

### Lists & Indexing Lists
Lists are lists, you can put data in lists, whether that be string, float, or integers. You can put a list in list, a function in list. You name it!
A list within a list is called a "NESTED LIST"!

Nested List:
- List_AB:
    - List A: 1, "બે", "三"
    - List_B: "Cuatro", 5, "Sechs"

In [24]:
# Let's make some list of numbers
List_A = [1, "બે", "三"]
List_B = list(("Cuatro", 5, "Sechs"))

print(List_A, List_B)
print(type(List_A), type(List_B))

# We can put 2 list into 1 list!
List_AB = [List_A, List_B]

print(List_AB)
print(type(List_AB))

# How do we access list?
List_B[0]
print(f"The first element of List_B is: {List_B[0]}")
print(f"The last element of List_B is: {List_B[-1]}")

# Python counts from 0, List_A has 4 items in it
List_A[3]

[1, 'બે', '三'] ['Cuatro', 5, 'Sechs']
<class 'list'> <class 'list'>
[[1, 'બે', '三'], ['Cuatro', 5, 'Sechs']]
<class 'list'>
The first element of List_B is: Cuatro
The last element of List_B is: Sechs


IndexError: list index out of range

In [25]:
# Can we access a range of elements?
# Lets combine List_A and List_B into List_C
List_C = List_A + List_B
print(List_C)

print(f"The lenght of our new list is {len(List_C)}")

# But I just want 5 and Sechs?
# [1:4] Starts at 4, stops at 6, 6 is not included
print(List_C[4], List_C[5])
print(List_C[4:6])

[1, 'બે', '三', 'Cuatro', 5, 'Sechs']
The lenght of our new list is 6
5 Sechs
[5, 'Sechs']


### Iteration and for loops
The point of putting data into a list is not only to able to access it easily and organise it
We can also ITERATE through it!
We do a lot of iteration in programming because this is what makes programming data > Excel

In [26]:
# for loop
for i in List_A:
    print(i)

# Do you want an index maybe?
# Remember python counts from 0
for idx, i in enumerate(List_A):
    print(idx, i)

1
બે
三
0 1
1 બે
2 三


In [27]:
# Simultaneous iteration
for A, B in zip(List_AB[0], List_AB[1]):
    print(A, B)

1 Cuatro
બે 5
三 Sechs


In [28]:
# We can change things in a loop!
for i in List_C:
    if type(i) == str:
        print(i)

બે
三
Cuatro
Sechs


In [30]:
# If and elif (else-if) allows you to create condition within the for loop iteration
for i in List_C:
    if type(i) == str:
        print(f"The data {i} is a string")
    elif type(i) == int:
        print(f"The data {i} is an integer")

print("\n Now with Enumeration")

for idx, j in enumerate(List_C):
    if type(j) == str:
        print(f"The data {j} at position {idx + 1} is a string")
    elif type(j) == int:
        print(f"The data {j} at position {idx + 1} is an integer")

The data 1 is an integer
The data બે is a string
The data 三 is a string
The data Cuatro is a string
The data 5 is an integer
The data Sechs is a string

 Now with Enumeration
The data 1 at position 1 is an integer
The data બે at position 2 is a string
The data 三 at position 3 is a string
The data Cuatro at position 4 is a string
The data 5 at position 5 is an integer
The data Sechs at position 6 is a string


### Numpy arrays & Indexing arrays
Numpy arrays are essentially Lists, but Lists with sizes that cannot be changed <br>
Arrays are more suitable for mathematical application because they ensure size <br>
We can have arrays with from 1-dimension to as many as you want <br>
That means we can use arrays to represent matrixes

In [31]:
array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A)
print(type(array_A))

# We can access array elements just like we did with List!
print(array_A[0])
print(array_B[0:2])

# We can even fill empty arrays with 1s and 0s and create arrays in our desired shape
# I want an array with 1-dimension of five 1
oneD_array = np.ones(5)
print(oneD_array)

# I want a 3 row and 3 column (3 by 3) matrix with 0s
twoD_array = np.zeros((3, 3))
print(twoD_array)

[1 2 3]
<class 'numpy.ndarray'>
1
[4 5]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [50]:
# More creative ways of making arrays

# Array range from 0 to 29
array_C = np.arange(30)
print(array_C)

# Array range from 4 to 400 with an interval of 20
# We can see the output is just shy of 400
array_D = np.arange(4, 400, 20)
print(array_D)

# Random 2-dimension array of 5 by 5
random_array = np.random.rand(5, 5)
print(random_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  4  24  44  64  84 104 124 144 164 184 204 224 244 264 284 304 324 344
 364 384]
[[0.53476439 0.33130651 0.88715264 0.55860861 0.5578236 ]
 [0.11533255 0.27006608 0.10272398 0.28113251 0.90394257]
 [0.16919041 0.26176463 0.96653513 0.72430497 0.85176908]
 [0.51906424 0.61578073 0.05866365 0.45988019 0.35889384]
 [0.67100903 0.8412291  0.43328698 0.6505899  0.43065478]]


In [63]:
# Random 3-dimesnion array of 10 by 10 by 3 (layer, row, column)
# With maximum integer limit of 500
ThreeD_RandArray = np.random.randint(500, size = (3, 10, 10))
print(ThreeD_RandArray)

[[[305 382 359 151 401 327 432 128 422 254]
  [124 333 188 252 262 371  44 154 266 103]
  [305  41 329 173 215 355 153 241 183 104]
  [ 60 138 111  79 301 360 433 480 433  57]
  [425 285 395 449  70 135 487   2 369 144]
  [145  24 496  26 340 313  61 403 143 443]
  [447 386 139 428 402 189 326 333 498 489]
  [350 227  91 435 394 281 404 192  64 350]
  [361  30 271  46 284 475 184 232 409 237]
  [429 484 229 261  78   8 178  16 407 107]]

 [[362  38 100 262 364 214 280 400   5 170]
  [ 32 309 255 253 457 407 141 288 100 272]
  [468 225 105 459 229 483 386  43 384 138]
  [ 47 246 239 211 325 395 400 420  96  14]
  [459 486 472 336 405 415 353 108 137 288]
  [298   3 484 210 416 304 418  99 384 151]
  [ 58 435 396  32 418 152 128 443 351 139]
  [472  51 382 416 176 201 224 343 242 399]
  [207 213 426 152 365   4  16 175 242  76]
  [ 46 371 335 139  29 373 493  23 306  68]]

 [[358  23 244  16 143 255 172 258 493 233]
  [454 466 464  93 265 333 271  34 305 457]
  [124 220 220  86  49 151 1

In [66]:
# Indexing 1D array
print(array_C[29])
print(array_C[-1])

print(array_C[29] == array_C[-1])

# Indexing 2D arrays
# Row 4, column 4
print(random_array[3, 3])

# Can we find the position from the value?
print(np.where(array_C == 29))

# How about 3-Dimensional arrays?
#[layer, row, column]
print(ThreeD_RandArray[1, 4, 0])

# Finding value from 3D-array position
print(np.where(ThreeD_RandArray == 459))

# I just want the 1st row of all 3 layers
print(ThreeD_RandArray[:, 0, ])

29
29
True
0.4598801911186743
(array([29], dtype=int64),)
459
(array([1, 1], dtype=int64), array([2, 4], dtype=int64), array([3, 0], dtype=int64))
[[305 382 359 151 401 327 432 128 422 254]
 [362  38 100 262 364 214 280 400   5 170]
 [358  23 244  16 143 255 172 258 493 233]]


### DataFrames
DataFrames == Tables == spreadsheet == excels <br>
DataFrames is a grid with a value of data in each cell, this table contains rows and column indexed <br>
We will be using the package pandas to create and access dataframes!

In [33]:
# Pandas DataFrame
# Let's built upon what we just learnt!
# Can we put List_A and List_B into a table?
Table = pd.DataFrame(twoD_array)

Table

0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0

In [34]:
# We can use multiple type of creating numpy arrays into making a dataframe!

df = pd.DataFrame({"col1": np.array([-4, 2, 3], dtype = np.int64),
                   "col2": np.arange(4, 7, 1, dtype = np.uint64),
                   "col3": np.zeros(3, dtype = np.float64),
                   "col4": np.array([True, False, False], dtype = bool)})
 
#import pyarrow as pa
## Pandas 2.0 and Arrow
#
#df = pd.DataFrame({"col1": pa.array([-193479, 5987349, 1291], type = "int64"),
#                   "col2": pa.array(np.arange(4, 7, 1), type = "uint64"),
#                   "col3": pa.array(np.zeros(3), type = "float64"),
#                   "col4": pa.array([True, False, False], type = "bool")})

print(df)

print(df.info())

   col1  col2  col3   col4
0    -4     4   0.0   True
1     2     5   0.0  False
2     3     6   0.0  False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    3 non-null      int64  
 1   col2    3 non-null      uint64 
 2   col3    3 non-null      float64
 3   col4    3 non-null      bool   
dtypes: bool(1), float64(1), int64(1), uint64(1)
memory usage: 207.0 bytes
None


### Let's look at E&S Data

In [ ]:
# Pandas 2.0
ESData = pd.read_csv(f"{data_raw}/ESData_sample.csv", engine = "pyarrow", dtype_backend = "pyarrow", sep = ";")
#ESData = pd.read_csv(f"{data_raw}/ESData_sample.csv", sep = ";")

ESData.sample(n = 8)

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
