In [1]:
#####################################
#02 Data order, list, df and wrangle#
#Maintainer: Christopher Chan       #
#Date: 2023-04-19                   #
#Version: 0.0.2                     #
#####################################

# Import all necessary packages
import os, sys, re
import random
import pathlib
import numpy as np
import pandas as pd
#import pyarrow as pa

# Load all the paths we might use later
data_raw = pathlib.Path("../data/raw")
data_external = pathlib.Path("../data/external")

## Welcome to 02_Wrangle!
Now that we have learnt the basics of python data types and syntax, we can actually work with some data!
Python data are organised in several formats:
- Lists, Arrays <br>
<t> Lists and arrays can hold multiple data within it, lists of lists, and lists of objects can also be made <br>
<t> Lists and arrays are iterable objects, (i.e. you can print it one by one)

- Dictionaries
- Matrixes
- DataFrames

In [2]:
# Let's make some list of numbers
List_A = [1, "two", 3]
List_B = list(("Cuatro", 5, "Sechs"))

print(List_A, List_B)
print(type(List_A), type(List_B))

# We can put 2 list into 1 list!
List_AB = [List_A, List_B]

print(List_AB)
print(type(List_AB))

# How do we access list?
List_B[0]
print(f"The first element of List_B is: {List_B[0]}")
print(f"The last element of List_B is: {List_B[-1]}")

# Python counts from 0, List_A has 4 items in it
List_A[3]

[1, 'two', 3] ['Cuatro', 5, 'Sechs']
<class 'list'> <class 'list'>
[[1, 'two', 3], ['Cuatro', 5, 'Sechs']]
<class 'list'>
The first element of List_B is: Cuatro
The last element of List_B is: Sechs


IndexError: list index out of range

In [10]:
# Can we access a range of elements?
# Lets combine List_A and List_B into List_C
List_C = List_A + List_B
print(List_C)

print(f"The lenght of our new list is {len(List_C)}")

# But I just want 5 and Sechs?
# [1:4] Starts at 4, stops at 6, 6 is not included
print(List_C[4], List_C[5])
print(List_C[4:6])

[1, 'two', 3, 'Cuatro', 5, 'Sechs']
The lenght of our new list is 6
5 Sechs
[5, 'Sechs']


### Iteration and for loops
The point of putting data into a list is not only to able to access it easily and organise it
We can also ITERATE through it!
We do a lot of iteration in programming because this is what makes programming data > Excel

In [ ]:
# for loop
for i in List_A:
    print(i)

# Do you want an index maybe?
# Remember python counts from 0
for idx, i in enumerate(List_A):
    print(idx, i)

In [ ]:
# Simultaneous iteration
for A, B in zip(List_AB[0], List_AB[1]):
    print(A, B)

### Numpy arrays
Numpy arrays are essentially Lists, but Lists with sizes that cannot be changed <br>
Arrays are more suitable for mathematical application because they ensure size <br>
We can have arrays with from 1-dimension to as many as you want <br>
That means we can use arrays to represent matrixes

In [26]:
array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A)
print(type(array_A))

# We can access array elements just like we did with List!
print(array_A[0])
print(array_B[0:2])

# We can even fill empty arrays with 1s and 0s and create arrays in our desired shape
# I want an array with 1-dimension of five 1
oneD_array = np.ones(5)
print(oneD_array)

# I want a 3 row and 3 column (3 by 3) matrix with 0s
twoD_array = np.zeros((3, 3))
print(twoD_array)

[1 2 3]
<class 'numpy.ndarray'>
1
[4 5]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### DataFrames
DataFrames == Tables == spreadsheet == excels <br>
DataFrames is a grid with a value of data in each cell, this table contains rows and column indexed <br>
We will be using the package pandas to create and access dataframes!

In [27]:
# Pandas DataFrame
# Let's built upon what we just learnt!
# Can we put List_A and List_B into a table?
Table = pd.DataFrame(twoD_array)

Table

0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0

In [57]:
# We can use multiple type of creating numpy arrays into making a dataframe!

df = pd.DataFrame({"col1": np.array([-4, 2, 3], dtype = np.int64),
                   "col2": np.arange(4, 7, 1, dtype = np.uint64),
                   "col3": np.zeros(3, dtype = np.float64),
                   "col4": np.array([True, False, False], dtype = bool)})
 
#import pyarrow as pa
## Pandas 2.0 and Arrow
#
#df = pd.DataFrame({"col1": pa.array([-193479, 5987349, 1291], type = "int64"),
#                   "col2": pa.array(np.arange(4, 7, 1), type = "uint64"),
#                   "col3": pa.array(np.zeros(3), type = "float64"),
#                   "col4": pa.array([True, False, False], type = "bool")})

print(df)

print(df.info())

   col1  col2  col3   col4
0    -4     4   0.0   True
1     2     5   0.0  False
2     3     6   0.0  False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    3 non-null      int64  
 1   col2    3 non-null      uint64 
 2   col3    3 non-null      float64
 3   col4    3 non-null      bool   
dtypes: bool(1), float64(1), int64(1), uint64(1)
memory usage: 207.0 bytes
None


### Let's look at E&S Data

In [ ]:
# Pandas 2.0
ESData = pd.read_csv(f"{data_raw}/ESData_sample.csv", engine = "pyarrow", dtype_backend = "pyarrow", sep = ";")
#ESData = pd.read_csv(f"{data_raw}/ESData_sample.csv", sep = ";")

ESData.sample(n = 8)